# Generated by Django 3.2.18 on 2023-04-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("data_browser", "0009_migrate_saved_views")]

    operations = [
        migrations.AddField(
            model_name="view", name="shared", field=models.BooleanField(default=False)
        )
    ]
