# Generated by Django 3.2.18 on 2023-04-17 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("data_browser", "0011_folder")]

    operations = [
        migrations.AlterModelOptions(
            name="view",
            options={
                "permissions": [
                    ("make_view_public", "Can make a saved view publicly available"),
                    ("share_view", "Can share a saved view with other users"),
                ]
            },
        )
    ]
