# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import Snapshot

snapshots = Snapshot()

snapshots["test_query_html config"] = {
    "allModelFields": {
        "auth.Group": {
            "fields": {
                "admin": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "admin",
                    "type": "html",
                },
                "id": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "number",
                    "prettyName": "id",
                    "type": "number",
                },
                "name": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "name",
                    "type": "string",
                },
            },
            "sortedFields": ["id", "admin", "name"],
        },
        "auth.User": {
            "fields": {
                "admin": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "admin",
                    "type": "html",
                },
                "date_joined": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "datetime",
                    "prettyName": "date_joined",
                    "type": "datetime",
                },
                "email": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "email",
                    "type": "string",
                },
                "first_name": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "first_name",
                    "type": "string",
                },
                "id": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "number",
                    "prettyName": "id",
                    "type": "number",
                },
                "is_active": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "boolean",
                    "prettyName": "is_active",
                    "type": "boolean",
                },
                "is_staff": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "boolean",
                    "prettyName": "is_staff",
                    "type": "boolean",
                },
                "is_superuser": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "boolean",
                    "prettyName": "is_superuser",
                    "type": "boolean",
                },
                "last_login": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "datetime",
                    "prettyName": "last_login",
                    "type": "datetime",
                },
                "last_name": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "last_name",
                    "type": "string",
                },
                "password": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "password",
                    "type": "string",
                },
                "username": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "username",
                    "type": "string",
                },
            },
            "sortedFields": [
                "id",
                "admin",
                "date_joined",
                "email",
                "first_name",
                "is_active",
                "is_staff",
                "is_superuser",
                "last_login",
                "last_name",
                "password",
                "username",
            ],
        },
        "boolean": {
            "fields": {
                "average": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "average",
                    "type": "number",
                },
                "sum": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "sum",
                    "type": "number",
                },
            },
            "sortedFields": ["average", "sum"],
        },
        "data_browser.View": {
            "fields": {
                "admin": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "admin",
                    "type": "html",
                },
                "created_time": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "datetime",
                    "prettyName": "created_time",
                    "type": "datetime",
                },
                "description": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "description",
                    "type": "string",
                },
                "fields": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "fields",
                    "type": "string",
                },
                "google_sheets_formula": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "google_sheets_formula",
                    "type": "string",
                },
                "id": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "id",
                    "type": "string",
                },
                "limit": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "number",
                    "prettyName": "limit",
                    "type": "number",
                },
                "model_name": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "model_name",
                    "type": "string",
                },
                "name": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "name",
                    "type": "string",
                },
                "open_view": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "open_view",
                    "type": "string",
                },
                "owner": {
                    "canPivot": False,
                    "concrete": False,
                    "model": "auth.User",
                    "prettyName": "owner",
                    "type": None,
                },
                "public": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "boolean",
                    "prettyName": "public",
                    "type": "boolean",
                },
                "public_link": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "public_link",
                    "type": "string",
                },
                "public_slug": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "public_slug",
                    "type": "string",
                },
                "query": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "query",
                    "type": "string",
                },
            },
            "sortedFields": [
                "id",
                "admin",
                "created_time",
                "description",
                "fields",
                "google_sheets_formula",
                "limit",
                "model_name",
                "name",
                "open_view",
                "owner",
                "public",
                "public_link",
                "public_slug",
                "query",
            ],
        },
        "date": {
            "fields": {
                "count": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "count",
                    "type": "number",
                },
                "day": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "day",
                    "type": "number",
                },
                "month": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "month",
                    "type": "month",
                },
                "quarter": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "quarter",
                    "type": "number",
                },
                "week_day": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "week_day",
                    "type": "weekday",
                },
                "year": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "year",
                    "type": "year",
                },
            },
            "sortedFields": ["count", "day", "month", "quarter", "week_day", "year"],
        },
        "datetime": {
            "fields": {
                "count": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "count",
                    "type": "number",
                },
                "date": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "date",
                    "type": "date",
                },
                "day": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "day",
                    "type": "number",
                },
                "hour": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "hour",
                    "type": "number",
                },
                "minute": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "minute",
                    "type": "number",
                },
                "month": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "month",
                    "type": "month",
                },
                "quarter": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "quarter",
                    "type": "number",
                },
                "second": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "second",
                    "type": "number",
                },
                "week_day": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "week_day",
                    "type": "weekday",
                },
                "year": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "year",
                    "type": "year",
                },
            },
            "sortedFields": [
                "count",
                "date",
                "day",
                "hour",
                "minute",
                "month",
                "quarter",
                "second",
                "week_day",
                "year",
            ],
        },
        "html": {"fields": {}, "sortedFields": []},
        "month": {"fields": {}, "sortedFields": []},
        "number": {
            "fields": {
                "average": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "average",
                    "type": "number",
                },
                "count": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "count",
                    "type": "number",
                },
                "max": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "max",
                    "type": "number",
                },
                "min": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "min",
                    "type": "number",
                },
                "std_dev": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "std_dev",
                    "type": "number",
                },
                "sum": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "sum",
                    "type": "number",
                },
                "variance": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "variance",
                    "type": "number",
                },
            },
            "sortedFields": [
                "average",
                "count",
                "max",
                "min",
                "std_dev",
                "sum",
                "variance",
            ],
        },
        "regex": {"fields": {}, "sortedFields": []},
        "string": {
            "fields": {
                "count": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "count",
                    "type": "number",
                }
            },
            "sortedFields": ["count"],
        },
        "tests.Address": {
            "fields": {
                "admin": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "admin",
                    "type": "html",
                },
                "andrew": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "andrew",
                    "type": "string",
                },
                "bob": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "bob",
                    "type": "string",
                },
                "city": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "city",
                    "type": "string",
                },
                "fred": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "fred",
                    "type": "string",
                },
                "id": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "number",
                    "prettyName": "id",
                    "type": "number",
                },
                "tom": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "tom",
                    "type": "string",
                },
            },
            "sortedFields": ["id", "admin", "andrew", "bob", "city", "fred", "tom"],
        },
        "tests.InAdmin": {
            "fields": {
                "admin": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "admin",
                    "type": "html",
                },
                "id": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "number",
                    "prettyName": "id",
                    "type": "number",
                },
                "name": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "name",
                    "type": "string",
                },
            },
            "sortedFields": ["id", "admin", "name"],
        },
        "tests.InlineAdmin": {
            "fields": {
                "id": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "number",
                    "prettyName": "id",
                    "type": "number",
                },
                "in_admin": {
                    "canPivot": False,
                    "concrete": False,
                    "model": "tests.InAdmin",
                    "prettyName": "in_admin",
                    "type": None,
                },
                "name": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "name",
                    "type": "string",
                },
            },
            "sortedFields": ["id", "in_admin", "name"],
        },
        "tests.Normal": {
            "fields": {
                "admin": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "admin",
                    "type": "html",
                },
                "id": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "number",
                    "prettyName": "id",
                    "type": "number",
                },
                "in_admin": {
                    "canPivot": False,
                    "concrete": False,
                    "model": "tests.InAdmin",
                    "prettyName": "in_admin",
                    "type": None,
                },
                "inline_admin": {
                    "canPivot": False,
                    "concrete": False,
                    "model": "tests.InlineAdmin",
                    "prettyName": "inline_admin",
                    "type": None,
                },
                "name": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "name",
                    "type": "string",
                },
            },
            "sortedFields": ["id", "admin", "in_admin", "inline_admin", "name"],
        },
        "tests.Producer": {
            "fields": {
                "address": {
                    "canPivot": False,
                    "concrete": False,
                    "model": "tests.Address",
                    "prettyName": "address",
                    "type": None,
                },
                "admin": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "admin",
                    "type": "html",
                },
                "frank": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "frank",
                    "type": "string",
                },
                "id": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "number",
                    "prettyName": "id",
                    "type": "number",
                },
                "name": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "name",
                    "type": "string",
                },
            },
            "sortedFields": ["id", "admin", "address", "frank", "name"],
        },
        "tests.Product": {
            "fields": {
                "admin": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "admin",
                    "type": "html",
                },
                "annotated": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "annotated",
                    "type": "string",
                },
                "created_time": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "datetime",
                    "prettyName": "created_time",
                    "type": "datetime",
                },
                "default_sku": {
                    "canPivot": False,
                    "concrete": False,
                    "model": "tests.SKU",
                    "prettyName": "default_sku",
                    "type": None,
                },
                "id": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "number",
                    "prettyName": "id",
                    "type": "number",
                },
                "is_onsale": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "is_onsale",
                    "type": "string",
                },
                "name": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "name",
                    "type": "string",
                },
                "only_in_list_view": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "only_in_list_view",
                    "type": "string",
                },
                "onsale": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "boolean",
                    "prettyName": "onsale",
                    "type": "boolean",
                },
                "producer": {
                    "canPivot": False,
                    "concrete": False,
                    "model": "tests.Producer",
                    "prettyName": "producer",
                    "type": None,
                },
                "size": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "number",
                    "prettyName": "size",
                    "type": "number",
                },
                "size_unit": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "size_unit",
                    "type": "string",
                },
            },
            "sortedFields": [
                "id",
                "admin",
                "annotated",
                "created_time",
                "default_sku",
                "is_onsale",
                "name",
                "only_in_list_view",
                "onsale",
                "producer",
                "size",
                "size_unit",
            ],
        },
        "tests.SKU": {
            "fields": {
                "id": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "number",
                    "prettyName": "id",
                    "type": "number",
                },
                "name": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "name",
                    "type": "string",
                },
                "product": {
                    "canPivot": False,
                    "concrete": False,
                    "model": "tests.Product",
                    "prettyName": "product",
                    "type": None,
                },
            },
            "sortedFields": ["id", "name", "product"],
        },
        "tests.Tag": {
            "fields": {
                "admin": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "admin",
                    "type": "html",
                },
                "id": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "number",
                    "prettyName": "id",
                    "type": "number",
                },
                "name": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "name",
                    "type": "string",
                },
            },
            "sortedFields": ["id", "admin", "name"],
        },
        "weekday": {"fields": {}, "sortedFields": []},
        "year": {"fields": {}, "sortedFields": []},
    },
    "baseUrl": "/data_browser/",
    "canMakePublic": True,
    "defaultRowLimit": 1000,
    "sentryDsn": None,
    "sortedModels": [
        "auth.Group",
        "auth.User",
        "data_browser.View",
        "tests.Address",
        "tests.InAdmin",
        "tests.InlineAdmin",
        "tests.Normal",
        "tests.Producer",
        "tests.Product",
        "tests.SKU",
        "tests.Tag",
    ],
    "types": {
        "boolean": {
            "defaultLookup": "equals",
            "defaultValue": True,
            "lookups": {
                "equals": {"type": "boolean"},
                "is_null": {"type": "boolean"},
                "not_equals": {"type": "boolean"},
            },
            "sortedLookups": ["equals", "not_equals", "is_null"],
        },
        "date": {
            "defaultLookup": "equals",
            "defaultValue": "today",
            "lookups": {
                "equals": {"type": "date"},
                "gt": {"type": "date"},
                "gte": {"type": "date"},
                "is_null": {"type": "boolean"},
                "lt": {"type": "date"},
                "lte": {"type": "date"},
                "not_equals": {"type": "date"},
            },
            "sortedLookups": [
                "equals",
                "not_equals",
                "gt",
                "gte",
                "lt",
                "lte",
                "is_null",
            ],
        },
        "datetime": {
            "defaultLookup": "equals",
            "defaultValue": "now",
            "lookups": {
                "equals": {"type": "datetime"},
                "gt": {"type": "datetime"},
                "gte": {"type": "datetime"},
                "is_null": {"type": "boolean"},
                "lt": {"type": "datetime"},
                "lte": {"type": "datetime"},
                "not_equals": {"type": "datetime"},
            },
            "sortedLookups": [
                "equals",
                "not_equals",
                "gt",
                "gte",
                "lt",
                "lte",
                "is_null",
            ],
        },
        "html": {
            "defaultLookup": None,
            "defaultValue": None,
            "lookups": {},
            "sortedLookups": [],
        },
        "month": {
            "defaultLookup": "equals",
            "defaultValue": "January",
            "lookups": {"equals": {"type": "month"}, "not_equals": {"type": "month"}},
            "sortedLookups": ["equals", "not_equals"],
        },
        "number": {
            "defaultLookup": "equals",
            "defaultValue": 0,
            "lookups": {
                "equals": {"type": "number"},
                "gt": {"type": "number"},
                "gte": {"type": "number"},
                "is_null": {"type": "boolean"},
                "lt": {"type": "number"},
                "lte": {"type": "number"},
                "not_equals": {"type": "number"},
            },
            "sortedLookups": [
                "equals",
                "not_equals",
                "gt",
                "gte",
                "lt",
                "lte",
                "is_null",
            ],
        },
        "regex": {
            "defaultLookup": None,
            "defaultValue": ".*",
            "lookups": {},
            "sortedLookups": [],
        },
        "string": {
            "defaultLookup": "equals",
            "defaultValue": "",
            "lookups": {
                "contains": {"type": "string"},
                "ends_with": {"type": "string"},
                "equals": {"type": "string"},
                "is_null": {"type": "boolean"},
                "not_contains": {"type": "string"},
                "not_ends_with": {"type": "string"},
                "not_equals": {"type": "string"},
                "not_regex": {"type": "regex"},
                "not_starts_with": {"type": "string"},
                "regex": {"type": "regex"},
                "starts_with": {"type": "string"},
            },
            "sortedLookups": [
                "equals",
                "contains",
                "starts_with",
                "ends_with",
                "regex",
                "not_equals",
                "not_contains",
                "not_starts_with",
                "not_ends_with",
                "not_regex",
                "is_null",
            ],
        },
        "weekday": {
            "defaultLookup": "equals",
            "defaultValue": "Monday",
            "lookups": {
                "equals": {"type": "weekday"},
                "not_equals": {"type": "weekday"},
            },
            "sortedLookups": ["equals", "not_equals"],
        },
        "year": {
            "defaultLookup": "equals",
            "defaultValue": 2020,
            "lookups": {
                "equals": {"type": "year"},
                "gt": {"type": "year"},
                "gte": {"type": "year"},
                "is_null": {"type": "boolean"},
                "lt": {"type": "year"},
                "lte": {"type": "year"},
                "not_equals": {"type": "year"},
            },
            "sortedLookups": [
                "equals",
                "not_equals",
                "gt",
                "gte",
                "lt",
                "lte",
                "is_null",
            ],
        },
    },
}

snapshots["test_query_query query"] = {
    "fields": [
        {
            "path": ["size"],
            "pathStr": "size",
            "pivoted": False,
            "prettyPath": ["size"],
            "priority": 0,
            "sort": "dsc",
        },
        {
            "path": ["name"],
            "pathStr": "name",
            "pivoted": False,
            "prettyPath": ["name"],
            "priority": 1,
            "sort": "asc",
        },
        {
            "path": ["size_unit"],
            "pathStr": "size_unit",
            "pivoted": False,
            "prettyPath": ["size_unit"],
            "priority": None,
            "sort": None,
        },
    ],
    "filterErrors": [None, None],
    "filters": [
        {
            "lookup": "lt",
            "path": ["size"],
            "pathStr": "size",
            "prettyPath": ["size"],
            "value": "2",
        },
        {
            "lookup": "gt",
            "path": ["id"],
            "pathStr": "id",
            "prettyPath": ["id"],
            "value": "0",
        },
    ],
    "limit": 1000,
    "model": "tests.Product",
}

snapshots["test_query_html_no_perms config"] = {
    "allModelFields": {
        "boolean": {
            "fields": {
                "average": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "average",
                    "type": "number",
                },
                "sum": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "sum",
                    "type": "number",
                },
            },
            "sortedFields": ["average", "sum"],
        },
        "date": {
            "fields": {
                "count": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "count",
                    "type": "number",
                },
                "day": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "day",
                    "type": "number",
                },
                "month": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "month",
                    "type": "month",
                },
                "quarter": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "quarter",
                    "type": "number",
                },
                "week_day": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "week_day",
                    "type": "weekday",
                },
                "year": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "year",
                    "type": "year",
                },
            },
            "sortedFields": ["count", "day", "month", "quarter", "week_day", "year"],
        },
        "datetime": {
            "fields": {
                "count": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "count",
                    "type": "number",
                },
                "date": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "date",
                    "type": "date",
                },
                "day": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "day",
                    "type": "number",
                },
                "hour": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "hour",
                    "type": "number",
                },
                "minute": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "minute",
                    "type": "number",
                },
                "month": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "month",
                    "type": "month",
                },
                "quarter": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "quarter",
                    "type": "number",
                },
                "second": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "second",
                    "type": "number",
                },
                "week_day": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "week_day",
                    "type": "weekday",
                },
                "year": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "year",
                    "type": "year",
                },
            },
            "sortedFields": [
                "count",
                "date",
                "day",
                "hour",
                "minute",
                "month",
                "quarter",
                "second",
                "week_day",
                "year",
            ],
        },
        "html": {"fields": {}, "sortedFields": []},
        "month": {"fields": {}, "sortedFields": []},
        "number": {
            "fields": {
                "average": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "average",
                    "type": "number",
                },
                "count": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "count",
                    "type": "number",
                },
                "max": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "max",
                    "type": "number",
                },
                "min": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "min",
                    "type": "number",
                },
                "std_dev": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "std_dev",
                    "type": "number",
                },
                "sum": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "sum",
                    "type": "number",
                },
                "variance": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "variance",
                    "type": "number",
                },
            },
            "sortedFields": [
                "average",
                "count",
                "max",
                "min",
                "std_dev",
                "sum",
                "variance",
            ],
        },
        "regex": {"fields": {}, "sortedFields": []},
        "string": {
            "fields": {
                "count": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "count",
                    "type": "number",
                }
            },
            "sortedFields": ["count"],
        },
        "weekday": {"fields": {}, "sortedFields": []},
        "year": {"fields": {}, "sortedFields": []},
    },
    "baseUrl": "/data_browser/",
    "canMakePublic": False,
    "defaultRowLimit": 1000,
    "sentryDsn": None,
    "sortedModels": [],
    "types": {
        "boolean": {
            "defaultLookup": "equals",
            "defaultValue": True,
            "lookups": {
                "equals": {"type": "boolean"},
                "is_null": {"type": "boolean"},
                "not_equals": {"type": "boolean"},
            },
            "sortedLookups": ["equals", "not_equals", "is_null"],
        },
        "date": {
            "defaultLookup": "equals",
            "defaultValue": "today",
            "lookups": {
                "equals": {"type": "date"},
                "gt": {"type": "date"},
                "gte": {"type": "date"},
                "is_null": {"type": "boolean"},
                "lt": {"type": "date"},
                "lte": {"type": "date"},
                "not_equals": {"type": "date"},
            },
            "sortedLookups": [
                "equals",
                "not_equals",
                "gt",
                "gte",
                "lt",
                "lte",
                "is_null",
            ],
        },
        "datetime": {
            "defaultLookup": "equals",
            "defaultValue": "now",
            "lookups": {
                "equals": {"type": "datetime"},
                "gt": {"type": "datetime"},
                "gte": {"type": "datetime"},
                "is_null": {"type": "boolean"},
                "lt": {"type": "datetime"},
                "lte": {"type": "datetime"},
                "not_equals": {"type": "datetime"},
            },
            "sortedLookups": [
                "equals",
                "not_equals",
                "gt",
                "gte",
                "lt",
                "lte",
                "is_null",
            ],
        },
        "html": {
            "defaultLookup": None,
            "defaultValue": None,
            "lookups": {},
            "sortedLookups": [],
        },
        "month": {
            "defaultLookup": "equals",
            "defaultValue": "January",
            "lookups": {"equals": {"type": "month"}, "not_equals": {"type": "month"}},
            "sortedLookups": ["equals", "not_equals"],
        },
        "number": {
            "defaultLookup": "equals",
            "defaultValue": 0,
            "lookups": {
                "equals": {"type": "number"},
                "gt": {"type": "number"},
                "gte": {"type": "number"},
                "is_null": {"type": "boolean"},
                "lt": {"type": "number"},
                "lte": {"type": "number"},
                "not_equals": {"type": "number"},
            },
            "sortedLookups": [
                "equals",
                "not_equals",
                "gt",
                "gte",
                "lt",
                "lte",
                "is_null",
            ],
        },
        "regex": {
            "defaultLookup": None,
            "defaultValue": ".*",
            "lookups": {},
            "sortedLookups": [],
        },
        "string": {
            "defaultLookup": "equals",
            "defaultValue": "",
            "lookups": {
                "contains": {"type": "string"},
                "ends_with": {"type": "string"},
                "equals": {"type": "string"},
                "is_null": {"type": "boolean"},
                "not_contains": {"type": "string"},
                "not_ends_with": {"type": "string"},
                "not_equals": {"type": "string"},
                "not_regex": {"type": "regex"},
                "not_starts_with": {"type": "string"},
                "regex": {"type": "regex"},
                "starts_with": {"type": "string"},
            },
            "sortedLookups": [
                "equals",
                "contains",
                "starts_with",
                "ends_with",
                "regex",
                "not_equals",
                "not_contains",
                "not_starts_with",
                "not_ends_with",
                "not_regex",
                "is_null",
            ],
        },
        "weekday": {
            "defaultLookup": "equals",
            "defaultValue": "Monday",
            "lookups": {
                "equals": {"type": "weekday"},
                "not_equals": {"type": "weekday"},
            },
            "sortedLookups": ["equals", "not_equals"],
        },
        "year": {
            "defaultLookup": "equals",
            "defaultValue": 2020,
            "lookups": {
                "equals": {"type": "year"},
                "gt": {"type": "year"},
                "gte": {"type": "year"},
                "is_null": {"type": "boolean"},
                "lt": {"type": "year"},
                "lte": {"type": "year"},
                "not_equals": {"type": "year"},
            },
            "sortedLookups": [
                "equals",
                "not_equals",
                "gt",
                "gte",
                "lt",
                "lte",
                "is_null",
            ],
        },
    },
}

snapshots["test_query_ctx config"] = {
    "allModelFields": {
        "auth.Group": {
            "fields": {
                "admin": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "admin",
                    "type": "html",
                },
                "id": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "number",
                    "prettyName": "id",
                    "type": "number",
                },
                "name": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "name",
                    "type": "string",
                },
            },
            "sortedFields": ["id", "admin", "name"],
        },
        "auth.User": {
            "fields": {
                "admin": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "admin",
                    "type": "html",
                },
                "date_joined": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "datetime",
                    "prettyName": "date_joined",
                    "type": "datetime",
                },
                "email": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "email",
                    "type": "string",
                },
                "first_name": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "first_name",
                    "type": "string",
                },
                "id": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "number",
                    "prettyName": "id",
                    "type": "number",
                },
                "is_active": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "boolean",
                    "prettyName": "is_active",
                    "type": "boolean",
                },
                "is_staff": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "boolean",
                    "prettyName": "is_staff",
                    "type": "boolean",
                },
                "is_superuser": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "boolean",
                    "prettyName": "is_superuser",
                    "type": "boolean",
                },
                "last_login": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "datetime",
                    "prettyName": "last_login",
                    "type": "datetime",
                },
                "last_name": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "last_name",
                    "type": "string",
                },
                "password": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "password",
                    "type": "string",
                },
                "username": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "username",
                    "type": "string",
                },
            },
            "sortedFields": [
                "id",
                "admin",
                "date_joined",
                "email",
                "first_name",
                "is_active",
                "is_staff",
                "is_superuser",
                "last_login",
                "last_name",
                "password",
                "username",
            ],
        },
        "boolean": {
            "fields": {
                "average": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "average",
                    "type": "number",
                },
                "sum": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "sum",
                    "type": "number",
                },
            },
            "sortedFields": ["average", "sum"],
        },
        "data_browser.View": {
            "fields": {
                "admin": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "admin",
                    "type": "html",
                },
                "created_time": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "datetime",
                    "prettyName": "created_time",
                    "type": "datetime",
                },
                "description": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "description",
                    "type": "string",
                },
                "fields": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "fields",
                    "type": "string",
                },
                "google_sheets_formula": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "google_sheets_formula",
                    "type": "string",
                },
                "id": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "id",
                    "type": "string",
                },
                "limit": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "number",
                    "prettyName": "limit",
                    "type": "number",
                },
                "model_name": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "model_name",
                    "type": "string",
                },
                "name": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "name",
                    "type": "string",
                },
                "open_view": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "open_view",
                    "type": "string",
                },
                "owner": {
                    "canPivot": False,
                    "concrete": False,
                    "model": "auth.User",
                    "prettyName": "owner",
                    "type": None,
                },
                "public": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "boolean",
                    "prettyName": "public",
                    "type": "boolean",
                },
                "public_link": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "public_link",
                    "type": "string",
                },
                "public_slug": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "public_slug",
                    "type": "string",
                },
                "query": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "query",
                    "type": "string",
                },
            },
            "sortedFields": [
                "id",
                "admin",
                "created_time",
                "description",
                "fields",
                "google_sheets_formula",
                "limit",
                "model_name",
                "name",
                "open_view",
                "owner",
                "public",
                "public_link",
                "public_slug",
                "query",
            ],
        },
        "date": {
            "fields": {
                "count": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "count",
                    "type": "number",
                },
                "day": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "day",
                    "type": "number",
                },
                "month": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "month",
                    "type": "month",
                },
                "quarter": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "quarter",
                    "type": "number",
                },
                "week_day": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "week_day",
                    "type": "weekday",
                },
                "year": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "year",
                    "type": "year",
                },
            },
            "sortedFields": ["count", "day", "month", "quarter", "week_day", "year"],
        },
        "datetime": {
            "fields": {
                "count": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "count",
                    "type": "number",
                },
                "date": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "date",
                    "type": "date",
                },
                "day": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "day",
                    "type": "number",
                },
                "hour": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "hour",
                    "type": "number",
                },
                "minute": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "minute",
                    "type": "number",
                },
                "month": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "month",
                    "type": "month",
                },
                "quarter": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "quarter",
                    "type": "number",
                },
                "second": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "second",
                    "type": "number",
                },
                "week_day": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "week_day",
                    "type": "weekday",
                },
                "year": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "year",
                    "type": "year",
                },
            },
            "sortedFields": [
                "count",
                "date",
                "day",
                "hour",
                "minute",
                "month",
                "quarter",
                "second",
                "week_day",
                "year",
            ],
        },
        "html": {"fields": {}, "sortedFields": []},
        "month": {"fields": {}, "sortedFields": []},
        "number": {
            "fields": {
                "average": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "average",
                    "type": "number",
                },
                "count": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "count",
                    "type": "number",
                },
                "max": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "max",
                    "type": "number",
                },
                "min": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "min",
                    "type": "number",
                },
                "std_dev": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "std_dev",
                    "type": "number",
                },
                "sum": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "sum",
                    "type": "number",
                },
                "variance": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "variance",
                    "type": "number",
                },
            },
            "sortedFields": [
                "average",
                "count",
                "max",
                "min",
                "std_dev",
                "sum",
                "variance",
            ],
        },
        "regex": {"fields": {}, "sortedFields": []},
        "string": {
            "fields": {
                "count": {
                    "canPivot": False,
                    "concrete": True,
                    "model": None,
                    "prettyName": "count",
                    "type": "number",
                }
            },
            "sortedFields": ["count"],
        },
        "tests.Address": {
            "fields": {
                "admin": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "admin",
                    "type": "html",
                },
                "andrew": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "andrew",
                    "type": "string",
                },
                "bob": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "bob",
                    "type": "string",
                },
                "city": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "city",
                    "type": "string",
                },
                "fred": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "fred",
                    "type": "string",
                },
                "id": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "number",
                    "prettyName": "id",
                    "type": "number",
                },
                "tom": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "tom",
                    "type": "string",
                },
            },
            "sortedFields": ["id", "admin", "andrew", "bob", "city", "fred", "tom"],
        },
        "tests.InAdmin": {
            "fields": {
                "admin": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "admin",
                    "type": "html",
                },
                "id": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "number",
                    "prettyName": "id",
                    "type": "number",
                },
                "name": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "name",
                    "type": "string",
                },
            },
            "sortedFields": ["id", "admin", "name"],
        },
        "tests.InlineAdmin": {
            "fields": {
                "id": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "number",
                    "prettyName": "id",
                    "type": "number",
                },
                "in_admin": {
                    "canPivot": False,
                    "concrete": False,
                    "model": "tests.InAdmin",
                    "prettyName": "in_admin",
                    "type": None,
                },
                "name": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "name",
                    "type": "string",
                },
            },
            "sortedFields": ["id", "in_admin", "name"],
        },
        "tests.Normal": {
            "fields": {
                "admin": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "admin",
                    "type": "html",
                },
                "id": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "number",
                    "prettyName": "id",
                    "type": "number",
                },
                "in_admin": {
                    "canPivot": False,
                    "concrete": False,
                    "model": "tests.InAdmin",
                    "prettyName": "in_admin",
                    "type": None,
                },
                "inline_admin": {
                    "canPivot": False,
                    "concrete": False,
                    "model": "tests.InlineAdmin",
                    "prettyName": "inline_admin",
                    "type": None,
                },
                "name": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "name",
                    "type": "string",
                },
            },
            "sortedFields": ["id", "admin", "in_admin", "inline_admin", "name"],
        },
        "tests.Producer": {
            "fields": {
                "address": {
                    "canPivot": False,
                    "concrete": False,
                    "model": "tests.Address",
                    "prettyName": "address",
                    "type": None,
                },
                "admin": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "admin",
                    "type": "html",
                },
                "frank": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "frank",
                    "type": "string",
                },
                "id": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "number",
                    "prettyName": "id",
                    "type": "number",
                },
                "name": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "name",
                    "type": "string",
                },
            },
            "sortedFields": ["id", "admin", "address", "frank", "name"],
        },
        "tests.Product": {
            "fields": {
                "admin": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "admin",
                    "type": "html",
                },
                "annotated": {
                    "canPivot": True,
                    "concrete": True,
                    "model": None,
                    "prettyName": "annotated",
                    "type": "string",
                },
                "created_time": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "datetime",
                    "prettyName": "created_time",
                    "type": "datetime",
                },
                "default_sku": {
                    "canPivot": False,
                    "concrete": False,
                    "model": "tests.SKU",
                    "prettyName": "default_sku",
                    "type": None,
                },
                "id": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "number",
                    "prettyName": "id",
                    "type": "number",
                },
                "is_onsale": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "is_onsale",
                    "type": "string",
                },
                "name": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "name",
                    "type": "string",
                },
                "only_in_list_view": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "only_in_list_view",
                    "type": "string",
                },
                "onsale": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "boolean",
                    "prettyName": "onsale",
                    "type": "boolean",
                },
                "producer": {
                    "canPivot": False,
                    "concrete": False,
                    "model": "tests.Producer",
                    "prettyName": "producer",
                    "type": None,
                },
                "size": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "number",
                    "prettyName": "size",
                    "type": "number",
                },
                "size_unit": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "size_unit",
                    "type": "string",
                },
            },
            "sortedFields": [
                "id",
                "admin",
                "annotated",
                "created_time",
                "default_sku",
                "is_onsale",
                "name",
                "only_in_list_view",
                "onsale",
                "producer",
                "size",
                "size_unit",
            ],
        },
        "tests.SKU": {
            "fields": {
                "id": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "number",
                    "prettyName": "id",
                    "type": "number",
                },
                "name": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "name",
                    "type": "string",
                },
                "product": {
                    "canPivot": False,
                    "concrete": False,
                    "model": "tests.Product",
                    "prettyName": "product",
                    "type": None,
                },
            },
            "sortedFields": ["id", "name", "product"],
        },
        "tests.Tag": {
            "fields": {
                "admin": {
                    "canPivot": True,
                    "concrete": False,
                    "model": None,
                    "prettyName": "admin",
                    "type": "html",
                },
                "id": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "number",
                    "prettyName": "id",
                    "type": "number",
                },
                "name": {
                    "canPivot": True,
                    "concrete": True,
                    "model": "string",
                    "prettyName": "name",
                    "type": "string",
                },
            },
            "sortedFields": ["id", "admin", "name"],
        },
        "weekday": {"fields": {}, "sortedFields": []},
        "year": {"fields": {}, "sortedFields": []},
    },
    "baseUrl": "/data_browser/",
    "canMakePublic": True,
    "defaultRowLimit": 1000,
    "sentryDsn": None,
    "sortedModels": [
        "auth.Group",
        "auth.User",
        "data_browser.View",
        "tests.Address",
        "tests.InAdmin",
        "tests.InlineAdmin",
        "tests.Normal",
        "tests.Producer",
        "tests.Product",
        "tests.SKU",
        "tests.Tag",
    ],
    "types": {
        "boolean": {
            "defaultLookup": "equals",
            "defaultValue": True,
            "lookups": {
                "equals": {"type": "boolean"},
                "is_null": {"type": "boolean"},
                "not_equals": {"type": "boolean"},
            },
            "sortedLookups": ["equals", "not_equals", "is_null"],
        },
        "date": {
            "defaultLookup": "equals",
            "defaultValue": "today",
            "lookups": {
                "equals": {"type": "date"},
                "gt": {"type": "date"},
                "gte": {"type": "date"},
                "is_null": {"type": "boolean"},
                "lt": {"type": "date"},
                "lte": {"type": "date"},
                "not_equals": {"type": "date"},
            },
            "sortedLookups": [
                "equals",
                "not_equals",
                "gt",
                "gte",
                "lt",
                "lte",
                "is_null",
            ],
        },
        "datetime": {
            "defaultLookup": "equals",
            "defaultValue": "now",
            "lookups": {
                "equals": {"type": "datetime"},
                "gt": {"type": "datetime"},
                "gte": {"type": "datetime"},
                "is_null": {"type": "boolean"},
                "lt": {"type": "datetime"},
                "lte": {"type": "datetime"},
                "not_equals": {"type": "datetime"},
            },
            "sortedLookups": [
                "equals",
                "not_equals",
                "gt",
                "gte",
                "lt",
                "lte",
                "is_null",
            ],
        },
        "html": {
            "defaultLookup": None,
            "defaultValue": None,
            "lookups": {},
            "sortedLookups": [],
        },
        "month": {
            "defaultLookup": "equals",
            "defaultValue": "January",
            "lookups": {"equals": {"type": "month"}, "not_equals": {"type": "month"}},
            "sortedLookups": ["equals", "not_equals"],
        },
        "number": {
            "defaultLookup": "equals",
            "defaultValue": 0,
            "lookups": {
                "equals": {"type": "number"},
                "gt": {"type": "number"},
                "gte": {"type": "number"},
                "is_null": {"type": "boolean"},
                "lt": {"type": "number"},
                "lte": {"type": "number"},
                "not_equals": {"type": "number"},
            },
            "sortedLookups": [
                "equals",
                "not_equals",
                "gt",
                "gte",
                "lt",
                "lte",
                "is_null",
            ],
        },
        "regex": {
            "defaultLookup": None,
            "defaultValue": ".*",
            "lookups": {},
            "sortedLookups": [],
        },
        "string": {
            "defaultLookup": "equals",
            "defaultValue": "",
            "lookups": {
                "contains": {"type": "string"},
                "ends_with": {"type": "string"},
                "equals": {"type": "string"},
                "is_null": {"type": "boolean"},
                "not_contains": {"type": "string"},
                "not_ends_with": {"type": "string"},
                "not_equals": {"type": "string"},
                "not_regex": {"type": "regex"},
                "not_starts_with": {"type": "string"},
                "regex": {"type": "regex"},
                "starts_with": {"type": "string"},
            },
            "sortedLookups": [
                "equals",
                "contains",
                "starts_with",
                "ends_with",
                "regex",
                "not_equals",
                "not_contains",
                "not_starts_with",
                "not_ends_with",
                "not_regex",
                "is_null",
            ],
        },
        "weekday": {
            "defaultLookup": "equals",
            "defaultValue": "Monday",
            "lookups": {
                "equals": {"type": "weekday"},
                "not_equals": {"type": "weekday"},
            },
            "sortedLookups": ["equals", "not_equals"],
        },
        "year": {
            "defaultLookup": "equals",
            "defaultValue": 2020,
            "lookups": {
                "equals": {"type": "year"},
                "gt": {"type": "year"},
                "gte": {"type": "year"},
                "is_null": {"type": "boolean"},
                "lt": {"type": "year"},
                "lte": {"type": "year"},
                "not_equals": {"type": "year"},
            },
            "sortedLookups": [
                "equals",
                "not_equals",
                "gt",
                "gte",
                "lt",
                "lte",
                "is_null",
            ],
        },
    },
}

snapshots["test_query_csv_pivot_permutations[----] key"] = [[""]]

snapshots["test_query_csv_pivot_permutations[---b] key"] = [
    ["id count", "size max"],
    ["0.0", ""],
]

snapshots["test_query_csv_pivot_permutations[--c-] key"] = [
    ["created_time month"],
    [""],
]

snapshots["test_query_csv_pivot_permutations[--cb] key"] = [
    ["created_time month"],
    [""],
]

snapshots["test_query_csv_pivot_permutations[-r--] key"] = [["created_time year"]]

snapshots["test_query_csv_pivot_permutations[-r-b] key"] = [
    ["created_time year", "id count", "size max"]
]

snapshots["test_query_csv_pivot_permutations[-rc-] key"] = [
    ["created_time month"],
    ["created_time year"],
]

snapshots["test_query_csv_pivot_permutations[-rcb] key"] = [
    ["created_time month"],
    ["created_time year"],
]

snapshots["test_query_csv_pivot_permutations[d---] key"] = [[""]]

snapshots["test_query_csv_pivot_permutations[d--b] key"] = [
    ["id count", "size max"],
    ["6.0", "6.0"],
]

snapshots["test_query_csv_pivot_permutations[d-c-] key"] = [
    ["created_time month", "January", "Feburary"],
    [""],
    [""],
]

snapshots["test_query_csv_pivot_permutations[d-cb] key"] = [
    ["created_time month", "January", "", "Feburary", ""],
    ["", "id count", "size max", "id count", "size max"],
    ["", "4.0", "6.0", "2.0", "3.0"],
]

snapshots["test_query_csv_pivot_permutations[dr--] key"] = [
    ["created_time year"],
    ["2020.0"],
    ["2021.0"],
]

snapshots["test_query_csv_pivot_permutations[dr-b] key"] = [
    ["created_time year", "id count", "size max"],
    ["2020.0", "3.0", "3.0"],
    ["2021.0", "3.0", "6.0"],
]

snapshots["test_query_csv_pivot_permutations[drc-] key"] = [
    ["created_time month", "January", "Feburary"],
    ["created_time year"],
    ["2020.0"],
    ["2021.0"],
]

snapshots["test_query_csv_pivot_permutations[drcb] key"] = [
    ["created_time month", "January", "", "Feburary", ""],
    ["created_time year", "id count", "size max", "id count", "size max"],
    ["2020.0", "1.0", "1.0", "2.0", "3.0"],
    ["2021.0", "3.0", "6.0", "", ""],
]

snapshots["test_query_json data"] = {
    "body": [[{}, {}]],
    "cols": [{}],
    "fields": [
        {
            "path": ["size"],
            "pathStr": "size",
            "pivoted": False,
            "prettyPath": ["size"],
            "priority": 0,
            "sort": "dsc",
        },
        {
            "path": ["name"],
            "pathStr": "name",
            "pivoted": False,
            "prettyPath": ["name"],
            "priority": 1,
            "sort": "asc",
        },
        {
            "path": ["size_unit"],
            "pathStr": "size_unit",
            "pivoted": False,
            "prettyPath": ["size_unit"],
            "priority": None,
            "sort": None,
        },
    ],
    "filterErrors": [None, None],
    "filters": [
        {
            "lookup": "lt",
            "path": ["size"],
            "pathStr": "size",
            "prettyPath": ["size"],
            "value": "2",
        },
        {
            "lookup": "gt",
            "path": ["id"],
            "pathStr": "id",
            "prettyPath": ["id"],
            "value": "0",
        },
    ],
    "length": 2,
    "limit": 1000,
    "model": "tests.Product",
    "rows": [
        {"name": "a", "size": 1.0, "size_unit": "g"},
        {"name": "b", "size": 1.0, "size_unit": "g"},
    ],
}

snapshots["test_query_json_pivot data"] = {
    "body": [
        [{"id__count": 1.0, "size__max": 1.0}, {"id__count": 3.0, "size__max": 6.0}],
        [{"id__count": 2.0, "size__max": 3.0}, None],
    ],
    "cols": [{"created_time__month": "January"}, {"created_time__month": "Feburary"}],
    "fields": [
        {
            "path": ["created_time", "year"],
            "pathStr": "created_time__year",
            "pivoted": False,
            "prettyPath": ["created_time", "year"],
            "priority": 0,
            "sort": "asc",
        },
        {
            "path": ["created_time", "month"],
            "pathStr": "created_time__month",
            "pivoted": True,
            "prettyPath": ["created_time", "month"],
            "priority": 1,
            "sort": "asc",
        },
        {
            "path": ["id", "count"],
            "pathStr": "id__count",
            "pivoted": False,
            "prettyPath": ["id", "count"],
            "priority": None,
            "sort": None,
        },
        {
            "path": ["size", "max"],
            "pathStr": "size__max",
            "pivoted": False,
            "prettyPath": ["size", "max"],
            "priority": None,
            "sort": None,
        },
    ],
    "filterErrors": [],
    "filters": [],
    "length": 3,
    "limit": 1000,
    "model": "tests.Product",
    "rows": [{"created_time__year": 2020.0}, {"created_time__year": 2021.0}],
}
